In [1]:
# ==========================================================
# Credit Card Fraud Detection - Data Preprocessing
# ==========================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
# Load dataset

df = pd.read_csv("../data/raw/creditcard/creditcard.csv")

print(df.shape)

df.head()

(284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
# Missing values

print(df.isnull().sum().sum())

0

In [4]:
# Remove duplicate records

print("Before:", df.shape)

df = df.drop_duplicates()

print("After :", df.shape)

Before: (284807, 31)
After : (283726, 31)

In [5]:
# Features

X = df.drop("Class", axis=1)

# Target

y = df["Class"]

print(X.shape)
print(y.shape)

(283726, 30)
(283726,)

In [6]:
scaler = StandardScaler()

X["Time"] = scaler.fit_transform(X[["Time"]])

X["Amount"] = scaler.fit_transform(X[["Amount"]])

X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.996823,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244200
1,-1.996823,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342584
2,-1.996802,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.158900
3,-1.996802,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.139886
4,-1.996781,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073813

In [8]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

In [10]:
print("Training Set   :", X_train.shape)
print("Validation Set :", X_valid.shape)
print("Testing Set    :", X_test.shape)

Training Set   : (198608, 30)
Validation Set : (42559, 30)
Testing Set    : (42559, 30)

In [11]:
print("Training")

print(y_train.value_counts())

print("\nValidation")

print(y_valid.value_counts())

print("\nTesting")

print(y_test.value_counts())

Training
Class
0    198277
1       331
Name: count, dtype: int64

Validation
Class
0    42488
1       71
Name: count, dtype: int64

Testing
Class
0    42488
1       71
Name: count, dtype: int64

In [12]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [13]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_valid.to_csv("../data/processed/X_valid.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_valid.to_csv("../data/processed/y_valid.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

print("Processed datasets saved successfully.")

Processed datasets saved successfully.